### PR TITLE
Version 1.1.0 Parsley

### PR DESCRIPTION
**Pull request by hyejang**
`openff-1.1.0.offxml` and `openff_unconstrained-1.1.0.offxml` were added. Details  about the version 1.1.0 can be found in [openforcefield/openforcefield-forcebalance/releases/tag/v1.1.0](https://github.com/openforcefield/openforcefield-forcebalance/releases/tag/v1.1.0).

### CODE REVIEW

**Comment by hyejang** [comment]
@j-wags could you double-check if the PR looks correct?

**Comment by jchodera** [comment]
@hyejang : Was this a manual bugfix or an automated refit with new types?
According to our semantic versioning, if it was a manual bugfix, it would be 1.0.1, but if you refit the parameters, it should be 1.1.0.

**Comment by hyejang** [comment]
@jchodera I think you are right. I'll change the version number to 1.1.0. Thanks for pointing it out.

**Comment by j-wags** [comment]
Great. @hyejang, do you have a tarball with the original QM data, scripts, and environment for this? I think we'll want to make that a release in [openforcefield-forcebalance](https://github.com/openforcefield/openforcefield-forcebalance/), and link that in the release notes in this repo.

**Comment by j-wags** [comment]
Ahhh, I see, [the linked release](https://github.com/openforcefield/openforcefield-forcebalance/releases/tag/v1.1.0) was originally called 1.0.1, but had outdated/erroneous benchmarking results, so the release was modified and the assets were updated. I think this is fine, since the `openforcefield-forcebalance` repo is not hooked up to Zenodo, so the there won't be any conflicting sources of information out there about this release.

**Comment by jchodera** [comment]
Hooray! Thanks so much for tackling this, @hyejang! It's exciting to see the force fields keep getting better!

**Pull request merged**
