### PR TITLE
GitHub Actions migration

### PR DESCRIPTION
**Pull request by mattwthompson**
I shamelessly copied the script @jaimergp wrote for the toolkit and trimmed it down to this

### CODE REVIEW

**Comment by mattwthompson** [comment]
Strange, the pip install wasn't able to remove the conda install (`openforcefields` was installed as an `openforcefield` dependency), even though I'm pretty sure that's precisely how it worked with Travis

**Comment by mattwthompson** [comment]
Badges for this PR: [Build Status](https://github.com/openforcefield/openforcefields/actions?query=branch%3Agha+workflow%3ACI)

Badge for master after this PR (should be broken now): [Build Status](https://github.com/openforcefield/openforcefields/actions?query=branch%3Amaster+workflow%3ACI)  [DOI](https://doi.org/10.5281/zenodo.3473553)

**Comment by mattwthompson** [comment]
@jaimergp please look this over and see if I broke anything :)

**Comment by jaimergp** [comment]
Hi @mattwthompson, would you mind if we use this PR to try that GH Action that Daniel Smith suggested? I am adding that to https://github.com/MolSSI/cookiecutter-cms/pull/95 as well, so it might a nice "real word" check while we are at it, if you don't mind :) Shouldn't me much of a change:

- We need to add the action, which would replace the env setup:

```
    - name: Setup Conda Environment
      uses: goanpeca/setup-miniconda@v1
      with:
         activate-environment: test
         environment-file: devtools/conda-envs/test_env.yaml
         auto-activate-base: false
```

- Replace later `shell: bash` lines with `shell: bash -l {0}`

**Comment by jaimergp** [comment]
Wow, that was... unexpectedly great!

**Comment by dotsdl** [comment]
LGTM! Great work y'all! it's a very clean implementation. :grin:

**Comment by mattwthompson** [comment]
Thanks @jaimergp @dotsdl

**Pull request merged**
